name: Vitepress Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: "14"

    - name: Install dependencies
      run: yarn

    - name: Build Website
      run: yarn build

    - name: Deploy Website
      uses: crazy-max/ghaction-github-pages@v2
      env: 
        GITHUB_TOKEN: ${{ secrets.NOTES }}
      with: 
        target_branch: gh-pages
        build_dir: docs/.vitepress/dist
